/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    copy: typeof import('./components/DsChannelPreview copy.vue')['default']
    DsChannelPreview: typeof import('./components/DsChannelPreview.vue')['default']
    DsComment: typeof import('./components/DsComment.vue')['default']
    DsCreateChannelModal: typeof import('./components/DsCreateChannelModal.vue')['default']
    DsCreateFeedModal: typeof import('./components/DsCreateFeedModal.vue')['default']
    DsEditChannelModal: typeof import('./components/DsEditChannelModal.vue')['default']
    DsEditFeedModal: typeof import('./components/DsEditFeedModal.vue')['default']
    DsEditProfileModal: typeof import('./components/DsEditProfileModal.vue')['default']
    DsFeedPreview: typeof import('./components/DsFeedPreview.vue')['default']
    DsPostPreview: typeof import('./components/DsPostPreview.vue')['default']
    DsRating: typeof import('./components/DsRating.vue')['default']
    DsTag: typeof import('./components/DsTag.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./components/Tag.vue')['default']
  }
}
