import createClient from 'openapi-fetch';
import type { paths } from './schema'; // generated by openapi-typescript
import { authMiddleware } from './auth-middleware';

export const client = createClient<paths>({
    baseUrl: 'http://127.0.0.1:2288/api/v1/',
});

client.use(authMiddleware);

export const useApi = () => {
    const api = ref(client);
    return api;
};

// const {
//   data, // only present if 2XX response
//   error, // only present if 4XX or 5XX response
// } = await client.GET("/users", {
//   params: {

//   },
// });

// await client.PATCH("/users", {
//   body: {

//   },
// });
