/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение пользователя по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nickname?: string;
                            about?: string;
                            id?: string;
                            banned?: boolean;
                            avatar?: string;
                            email?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Частичное обновление полей пользователя */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    userId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        password?: string;
                        nickname?: string;
                        about?: string;
                        avatar?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Передан пустой объект для апдейта */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение комментария по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            id?: string;
                            postId?: string;
                            text?: string;
                            updated?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Удаление комментария по id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Частичное обновление полей комментария */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    commentId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        text?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение поста по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            tagIds?: string[];
                            id?: string;
                            text?: string;
                            title?: string;
                            updated?: string;
                            channelId?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Удаление поста по id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Частичное обновление полей поста по id */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        visible?: boolean;
                        tagIds?: string[];
                        text?: string;
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Передан пустой объект для апдейта */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Логин */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        password?: string;
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                        };
                    };
                };
                /** @description Пользователь не авторизован */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Пользователь забанен */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Пользователь не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение постов в ленте */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                };
                header?: never;
                path: {
                    /** @description description */
                    feedId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            tagIds?: string[];
                            id?: string;
                            text?: string;
                            title?: string;
                            updated?: string;
                            channelId?: string;
                        }[];
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{commentId}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Лайкнуть комментарий */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Убрать лайк у комментария */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    commentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение лент пользователя */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                    /** @description description */
                    pattern?: string;
                    /** @description description */
                    name?: string;
                };
                header?: never;
                path: {
                    /** @description description */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            tagIds?: string[];
                            name?: string;
                            id?: string;
                            channelIds?: string[];
                            updated?: string;
                        }[];
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение комментариев к посту */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                };
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            id?: string;
                            postId?: string;
                            text?: string;
                            updated?: string;
                        }[];
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Создать комментарий к посту */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        text?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            id?: string;
                            postId?: string;
                            text?: string;
                            updated?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Лайкнуть пост */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Убрать лайк с поста */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить ленту по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    feedId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            tagIds?: string[];
                            name?: string;
                            id?: string;
                            channelIds?: string[];
                            updated?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Удалить ленту по id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    feedId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Обновить ленту по id */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    feedId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        visible?: boolean;
                        tagIds?: string[];
                        name?: string;
                        channelIds?: string[];
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            visible?: boolean;
                            created?: string;
                            tagIds?: string[];
                            name?: string;
                            id?: string;
                            channelIds?: string[];
                            updated?: string;
                        };
                    };
                };
                /** @description Какие то из каналов ленты скрыты */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск по лентам */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                    /** @description description */
                    name?: string;
                    /** @description description */
                    pattern?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            tagIds?: string[];
                            name?: string;
                            id?: string;
                            channelIds?: string[];
                            updated?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Создать ленту */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        visible?: boolean;
                        tagIds?: string[];
                        name?: string;
                        channelIds?: string[];
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            tagIds?: string[];
                            name?: string;
                            id?: string;
                            channelIds?: string[];
                            updated?: string;
                        };
                    };
                };
                /** @description Какие то из каналов ленты скрыты */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить тег по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Удаление тега по id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Частичное обновление полей тега */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    tagId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/channels/{channelId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение постов в канале */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                    /** @description description */
                    title?: string;
                    /** @description description */
                    pattern?: string;
                };
                header?: never;
                path: {
                    /** @description description */
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            tagIds?: string[];
                            id?: string;
                            text?: string;
                            title?: string;
                            updated?: string;
                            channelId?: string;
                        }[];
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Создать пост в канале */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    channelId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        visible?: boolean;
                        tagIds?: string[];
                        text?: string;
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            scores?: {
                                [key: string]: number;
                            };
                            created?: string;
                            tagIds?: string[];
                            id?: string;
                            text?: string;
                            title?: string;
                            updated?: string;
                            channelId?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск по каналам */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                    /** @description description */
                    name?: string;
                    /** @description description */
                    pattern?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Создать канал */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        visible?: boolean;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить информацию о себе */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            permissions?: number;
                            created?: string;
                            nickname?: string;
                            about?: string;
                            id?: string;
                            banned?: boolean;
                            avatar?: string;
                            updated?: string;
                            email?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Частичное обновление информации о себе */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        password?: string;
                        nickname?: string;
                        about?: string;
                        avatar?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            permissions?: number;
                            created?: string;
                            nickname?: string;
                            about?: string;
                            id?: string;
                            banned?: boolean;
                            avatar?: string;
                            updated?: string;
                            email?: string;
                        };
                    };
                };
                /** @description Передан пустой объект для апдейта */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск по тегам */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                    /** @description description */
                    name?: string;
                    /** @description description */
                    pattern?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Создание тега */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        };
                    };
                };
                /** @description Тег с таким именем уже существуе */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск по каналам пользователя */
        get: {
            parameters: {
                query?: {
                    /** @description description */
                    page?: number;
                    /** @description description */
                    batch?: number;
                    /** @description description */
                    pattern?: string;
                    /** @description description */
                    name?: string;
                };
                header?: never;
                path: {
                    /** @description description */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        }[];
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        password?: string;
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                        };
                    };
                };
                /** @description Пользователь с таким email уже существует */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение канала по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ownerId?: string;
                            visible?: boolean;
                            created?: string;
                            name?: string;
                            id?: string;
                            updated?: string;
                        };
                    };
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Удаление канала по id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Частичное обновление полей канала */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description description */
                    channelId: string;
                };
                cookie?: never;
            };
            /** @description description */
            requestBody: {
                content: {
                    "application/json": {
                        visible?: boolean;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Успех */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не указано name и visible */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Нет доступа */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Не найдено */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
