version: "3"

networks:
  devspark-network:

services:
  mongo1:
    image: mongo
    restart: on-failure
    networks:
      devspark-network:
    ports:
      - "27017:27017"
    command: 'mongod --replSet rs0'
   
  mongo2:
    image: mongo
    restart: on-failure
    networks:
      devspark-network:
    ports:
      - "27018:27017"
    command: 'mongod --replSet rs0'

  server:
    build: ./src/server
    restart: on-failure
    networks:
      devspark-network:
    ports:
      - "8080:8080"
    volumes:
      - "./src/salt.pbkdf2:/usr/src/server/salt.pbkdf2"
      - "./src/auth.json:/usr/src/server/auth.json"
    depends_on:
      - mongo1
      
  mirror1:
    build: ./src/mirror
    restart: on-failure
    networks:
      devspark-network:
    ports:
      - "8070:8070"
    volumes:
      - "./src/salt.pbkdf2:/usr/src/mirror/salt.pbkdf2"
      - "./src/auth.json:/usr/src/mirror/auth.json"
    depends_on:
      - mongo2
      
  node1:
    build: ./src/replica
    restart: on-failure
    networks:
      devspark-network:
    environment:
        AUTH_CONFIG: "/auth/auth.json"
        SERVER_CONFIG: "/nodes/node1.json"
        SALT_FILE: "/salt/salt.pbkdf2"
    volumes:
      - "./src/salt.pbkdf2:/salt/salt.pbkdf2"
      - "./src/auth.json:/auth/auth.json"
      - "./src/node1.json:/nodes/node1.json"
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      - server
      
  node2:
    build: ./src/replica
    restart: on-failure
    networks:
      devspark-network:
    environment:
        AUTH_CONFIG: "/auth/auth.json"
        SERVER_CONFIG: "/nodes/node2.json"
        SALT_FILE: "/salt/salt.pbkdf2"
    volumes:
      - "./src/salt.pbkdf2:/salt/salt.pbkdf2"
      - "./src/auth.json:/auth/auth.json"
      - "./src/node2.json:/nodes/node2.json"
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      - server

  nginx:
    build: 
      context: ./src/nginx
      dockerfile: nginx.dockerfile
    networks:
      devspark-network:
    ports:
      - "2288:80"
    volumes:
      - "./src/client/public:/app/static"
      - "./README.md:/app/readme.md"
      - "./src/nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server
      - mirror1

  mongo-express:
    build:
      context: ./src/mongo-express
      dockerfile: mongo-express.dockerfile
    networks:
      devspark-network:
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    env_file:
      - ./src/mongo-express/mongo-express.env